### ISSUE TITLE
Kernel dies after startup with "Value out of range for char"

### ISSUE THREAD

**Issue by Sharpie** [roryk/clojupyter#2]
Whenever I try to launch a new Clojure kernel from the Jupyter notebook, it dies shortly after startup with the following backtrace:

```
[I 14:30:13.986 NotebookApp] Creating new notebook in
[I 14:30:14.905 NotebookApp] Kernel started: 4df3e57a-d621-4335-b725-fa142d1558ed
Input configuration: {:transport tcp, :iopub_port 54345, :key 8a12fb29-3024-4d10-82ea-0d090064cb86, :signature_scheme hmac-sha256, :shell_port 54344, :stdin_port 54346, :control_port 54347, :hb_port 54348, :ip 127.0.0.1}
Connecting heartbeat to tcp://127.0.0.1:54348
Connecting shell to tcp://127.0.0.1:54344
Connecting iopub to tcp://127.0.0.1:54345
Exception in thread "main" java.lang.IllegalArgumentException: Value out of range for char: -116
	at clojure.lang.RT.charCast(RT.java:929)
	at clojure.core$char.invoke(core.clj:3157)
	at clojure.core$map$fn__4207.invoke(core.clj:2487)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:60)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.boundedLength(RT.java:1654)
	at clojure.lang.RestFn.applyTo(RestFn.java:130)
	at clojure.core$apply.invoke(core.clj:617)
	at ipython_clojure.core$read_blob.invoke(core.clj:65)
	at ipython_clojure.core$read_until_delimiter$fn__1534.invoke(core.clj:71)
	at clojure.core$repeatedly$fn__4705.invoke(core.clj:4642)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:60)
	at clojure.lang.RT.seq(RT.java:484)
	at clojure.core$seq.invoke(core.clj:133)
	at clojure.core$take_while$fn__4236.invoke(core.clj:2564)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:60)
	at clojure.lang.RT.seq(RT.java:484)
	at clojure.core$seq.invoke(core.clj:133)
	at clojure.core$map$fn__4211.invoke(core.clj:2490)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:60)
	at clojure.lang.RT.seq(RT.java:484)
	at clojure.core$seq.invoke(core.clj:133)
	at clojure.core$dorun.invoke(core.clj:2780)
	at clojure.core$doall.invoke(core.clj:2796)
	at ipython_clojure.core$read_until_delimiter.invoke(core.clj:71)
	at ipython_clojure.core$read_raw_message.invoke(core.clj:120)
	at ipython_clojure.core$shell_loop.invoke(core.clj:224)
	at ipython_clojure.core$_main.doInvoke(core.clj:240)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at ipython_clojure.core.main(Unknown Source)
[W 14:30:25.008 NotebookApp] Timeout waiting for kernel_info reply from 4df3e57a-d621-4335-b725-fa142d1558ed
```

Running Jupyter 4.0.4 under Python 2.7.10 on OS X 10.10.5. Clojupyter `9cfd894` built with Leiningen 2.5.2 on Java 1.8.0_51.

**Comment by Sharpie** [comment]
The error is consistent, but the value does change. In all cases it looks like Clojupyter is trying to coerce a negative integer to a character value.

**Comment by roryk** [comment]
Hi @Sharpie,

I'm not sure what the source of this error is, Jupyter is sending an weird message, I think it comes along with the kernel_info request that it thinks is timing out.

We weren't following enough of the current messaging protocol to handle some of the extra stuff the notebook uses, so I implemented those. I am still getting the kernel_info request timeouts, but at least it the notebook is as functional as the console now.

Thanks!

**Comment by Sharpie** [comment]
Just updated to 4bb97c6 and the notebook is now successfully spawning Clojure kernels. Thanks!
