### ISSUE TITLE
Cannot exit when an exception is thrown.

### ISSUE THREAD

**Issue by jiegec** [roryk/clojupyter#5]
In [2]: (filter even? foo)
Exception in thread "main" java.lang.ClassCastException: java.lang.Long cannot be cast to clojure.lang.IFn
	at clojure.core$eval6.invoke(NO_SOURCE_FILE)
	at clojure.lang.Compiler.eval(Compiler.java:6619)
	at clojure.lang.Compiler.eval(Compiler.java:6582)
	at clojure.core$eval.invoke(core.clj:2852)
	at ipython_clojure.core$execute_request_handler$fn__1579$fn__1581.invoke(core.clj:213)
	at ipython_clojure.core$execute_request_handler$fn__1579.invoke(core.clj:212)
	at ipython_clojure.core$configure_shell_handler$fn__1595.invoke(core.clj:276)
	at ipython_clojure.core$shell_loop.invoke(core.clj:309)
	at ipython_clojure.core$_main.doInvoke(core.clj:323)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at ipython_clojure.core.main(Unknown Source)

^C^C^X^C^C^C^C^C^C^C

^C^C

**Comment by roryk** [comment]
Hi @jlegec,

This was partially fixed in 83718ef9f219. The errors are captured now so you can at least continue. I'll leave this open because a better fix would be to capture, print the error to the console and then continue so it works more like the normal REPL does.

**Comment by roryk** [comment]
Thanks, this should be all set now.

**Comment by jiegec** [comment]
IMO the error output should include error message.
